apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Bestilling av dialogmeldinger til fastleger og andre behandlere"
    dcat.data.nav.no/description: >-
      Topic inneholder bestilling av dialogmeldinger til fastleger og andre behandlere.
  name: isdialogmelding-behandler-dialogmelding-bestilling
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  pool: {{ kafkaPool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykefravr
      application: isdialogmelding
      access: readwrite
    - team: teamsykefravr
      application: isdialogmote
      access: write
