apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmelding
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isdialogmelding.intern.nav.no"
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
        - application: soknad-api
          namespace: aap
          cluster: prod-gcp
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: prod-fss
    outbound:
      external:
        - host: "mpls02.adeo.no"
          ports:
            - port: 1414
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "syfopartnerinfo.prod-fss-pub.nais.io"
        - host: "btsys.prod-fss-pub.nais.io"
      rules:
        - application: fastlegerest
        - application: istilgangskontroll
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: isdialogmelding-db
        diskAutoresize: true
  envFrom:
    - secret: isdialogmelding-serviceuser
    - secret: isdialogmelding-keystore-pwd
  filesFrom:
    - mountPath: /var/run/keystore
      secret: isdialogmelding-keystore
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: MQGATEWAY_NAME
      value: "MPLS02"
    - name: MQGATEWAY_HOSTNAME
      value: "mpls02.adeo.no"
    - name: MQGATEWAY_PORT
      value: "1414"
    - name: MQGATEWAY_CHANNEL_NAME
      value: "P_ISDIALOGMELDING"
    - name: MQ_KEYSTORE_PATH
      value: "/var/run/keystore/isdialogmelding-keystore.jks"
    - name: APPREC_QUEUE
      value: "QA.P_ISDIALOGMELDING.IU03_UTSENDING_REPLY"
    - name: MOTTAK_QUEUE_UTSENDING_QUEUENAME
      value: "QA.P414.IU03_UTSENDING"
    - name: AAP_SOKNAD_API_CLIENT_ID
      value: "prod-gcp:aap:soknad-api"
    - name: SYFOOPPFOLGINGSPLANSERVICE_CLIENT_ID
      value: "prod-fss:team-esyfo:syfooppfolgingsplanservice"
    - name: FASTLEGEREST_CLIENT_ID
      value: "prod-gcp.teamsykefravr.fastlegerest"
    - name: FASTLEGEREST_URL
      value: "http://fastlegerest"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SYFOPARTNERINFO_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfopartnerinfo"
    - name: SYFOPARTNERINFO_URL
      value: "https://syfopartnerinfo.prod-fss-pub.nais.io"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: BTSYS_CLIENT_ID
      value: "prod-fss.team-rocket.btsys"
    - name: BTSYS_ENDPOINT_URL
      value: "https://btsys.prod-fss-pub.nais.io"
