apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmelding
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isdialogmelding.intern.dev.nav.no"
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: soknad-api
          namespace: aap
          cluster: dev-gcp
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
    outbound:
      external:
        - host: "b27apvl220.preprod.local"
          ports:
            - name: MQ
              port: 1413
              protocol: TCP
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "syfopartnerinfo.dev-fss-pub.nais.io"
      rules:
        - application: fastlegerest
        - application: syfo-tilgangskontroll
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: isdialogmelding-db
        diskAutoresize: true
  envFrom:
    - secret: isdialogmelding-serviceuser
    - secret: isdialogmelding-keystore-pwd
  filesFrom:
    - mountPath: /var/run/keystore
      secret: isdialogmelding-keystore
  kafka:
    pool: nav-dev
  env:
    - name: KTOR_ENV
      value: "production"
    - name: MQGATEWAY_NAME
      value: "MQLS02"
    - name: MQGATEWAY_HOSTNAME
      value: "b27apvl220.preprod.local"
    - name: MQGATEWAY_PORT
      value: "1413"
    - name: MQGATEWAY_CHANNEL_NAME
      value: "Q1_ISDIALOGMELDING"
    - name: MQ_KEYSTORE_PATH
      value: "/var/run/keystore/isdialogmelding-keystore.jks"
    - name: APPREC_QUEUE
      value: "QA.Q1_ISDIALOGMELDING.IU03_UTSENDING_REPLY"
    - name: MOTTAK_QUEUE_UTSENDING_QUEUENAME
      value: "QA.Q414.IU03_UTSENDING"
    - name: AAP_SOKNAD_API_CLIENT_ID
      value: "dev-gcp:aap:soknad-api"
    - name: SYFOOPPFOLGINGSPLANSERVICE_CLIENT_ID
      value: "dev-fss:team-esyfo:syfooppfolgingsplanservice"
    - name: FASTLEGEREST_CLIENT_ID
      value: "dev-gcp.teamsykefravr.fastlegerest"
    - name: FASTLEGEREST_URL
      value: "http://fastlegerest"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: SYFOPARTNERINFO_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfopartnerinfo"
    - name: SYFOPARTNERINFO_URL
      value: "https://syfopartnerinfo.dev-fss-pub.nais.io"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "http://syfo-tilgangskontroll"
