ALTER TABLE BEHANDLER_DIALOGMELDING_ARBEIDSTAKER ADD COLUMN fornavn VARCHAR(255) NOT NULL;
ALTER TABLE BEHANDLER_DIALOGMELDING_ARBEIDSTAKER ADD COLUMN mellomnavn VARCHAR(255);
ALTER TABLE BEHANDLER_DIALOGMELDING_ARBEIDSTAKER ADD COLUMN etternavn VARCHAR(255) NOT NULL;
