CREATE INDEX IX_BEHANDLER_DIALOGMELDING_PARTNERID_HERID on BEHANDLER_DIALOGMELDING (partner_id, her_id);
CREATE INDEX IX_BEHANDLER_DIALOGMELDING_PARTNERID_HPRID on BEHANDLER_DIALOGMELDING (partner_id, hpr_id);
