ALTER TABLE BEHANDLER_KONTOR ADD COLUMN kilde_tidspunkt timestamptz;
UPDATE BEHANDLER_KONTOR SET kilde_tidspunkt=updated_at;
ALTER TABLE BEHANDLER_KONTOR ALTER COLUMN kilde_tidspunkt SET NOT NULL;

ALTER TABLE BEHANDLER ADD COLUMN kilde_tidspunkt timestamptz;
UPDATE BEHANDLER SET kilde_tidspunkt=updated_at;
ALTER TABLE BEHANDLER ALTER COLUMN kilde_tidspunkt SET NOT NULL;

ALTER TABLE BEHANDLER_ARBEIDSTAKER ADD COLUMN kilde_tidspunkt timestamptz;
UPDATE BEHANDLER_ARBEIDSTAKER SET kilde_tidspunkt=updated_at;
ALTER TABLE BEHANDLER_ARBEIDSTAKER ALTER COLUMN kilde_tidspunkt SET NOT NULL;
