ALTER TABLE BEHANDLER_KONTOR DROP COLUMN IF EXISTS kilde_tidspunkt;
ALTER TABLE BEHANDLER_KONTOR ADD COLUMN mottatt timestamptz;
UPDATE BEHANDLER_KONTOR SET mottatt=updated_at;
ALTER TABLE BEHANDLER_KONTOR ALTER COLUMN mottatt SET NOT NULL;

ALTER TABLE BEHANDLER DROP COLUMN IF EXISTS kilde_tidspunkt;
ALTER TABLE BEHANDLER ADD COLUMN mottatt timestamptz;
UPDATE BEHANDLER SET mottatt=updated_at;
ALTER TABLE BEHANDLER ALTER COLUMN mottatt SET NOT NULL;

ALTER TABLE BEHANDLER_ARBEIDSTAKER DROP COLUMN IF EXISTS kilde_tidspunkt;
ALTER TABLE BEHANDLER_ARBEIDSTAKER ADD COLUMN mottatt timestamptz;
UPDATE BEHANDLER_ARBEIDSTAKER SET mottatt=updated_at;
ALTER TABLE BEHANDLER_ARBEIDSTAKER ALTER COLUMN mottatt SET NOT NULL;
