CREATE INDEX IX_BEHANDLER_KONTOR_NAVN on BEHANDLER_KONTOR (navn);
CREATE INDEX IX_BEHANDLER_KONTOR_ORGNUMMER on BEHANDLER_KONTOR (orgnummer);
CREATE INDEX IX_BEHANDLER_FORNAVN on BEHANDLER (etternavn);
CREATE INDEX IX_BEHANDLER_ETTERNAVN on BEHANDLER (etternavn);
