ALTER TABLE BEHANDLER ADD COLUMN suspendert BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IX_BEHANDLER_PERSONIDENT on BEHANDLER (personident);

UPDATE BEHANDLER SET suspendert=true WHERE id IN (1433,4371,5575,11953,12244);
