UPDATE BEHANDLER_KONTOR SET dialogmelding_enabled=null,dialogmelding_enabled_locked=true WHERE ID=936;
UPDATE BEHANDLER_KONTOR SET dialogmelding_enabled=null,dialogmelding_enabled_locked=true WHERE ID=209;
UPDATE BEHANDLER_KONTOR SET dialogmelding_enabled=null,dialogmelding_enabled_locked=true WHERE ID=222;
UPDATE BEHANDLER_KONTOR SET dialogmelding_enabled=null,dialogmelding_enabled_locked=true WHERE ID=1234;
UPDATE BEHANDLER_KONTOR SET dialogmelding_enabled=null,dialogmelding_enabled_locked=true WHERE ID=503;
UPDATE BEHANDLER SET her_id='159749' where id=23009;
UPDATE BEHANDLER SET her_id='177974' where id=31244;
UPDATE BEHANDLER SET her_id='178768' where id=33079;
UPDATE BEHANDLER SET her_id='86655' where id=36753;
