name: kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/kafka.yaml'
      - '.nais/kafka/**'

permissions:
  id-token: write

jobs:
  deploy-kafka-dev:
    name: Deploy Kafka topic to NAIS dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy behandler-dialogmelding-bestilling dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/behandler-dialogmelding-bestilling.yaml
          VARS: .nais/kafka/dev.json

      - name: Deploy behandler-dialogmelding-status dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/behandler-dialogmelding-status.yaml
          VARS: .nais/kafka/dev.json

  deploy-kafka-prod:
    name: Deploy Kafka topic to NAIS prod-gcp
    needs: deploy-kafka-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy behandler-dialogmelding-bestilling prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/behandler-dialogmelding-bestilling.yaml
          VARS: .nais/kafka/prod.json

      - name: Deploy behandler-dialogmelding-status prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/behandler-dialogmelding-status.yaml
          VARS: .nais/kafka/prod.json
